AWSTemplateFormatVersion: '2010-09-09'
Description: Template para a criacao de um bucket s3 na AWS.

Resources:
  StickerBuyer:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: 'sticker-buyer'
      WebsiteConfiguration:
        IndexDocument: 'index.html'
        ErrorDocument: '404.html'

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StickerBuyer
      PolicyDocument:
        Id: PolicyForStickerBuyerBucket
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: arn:aws:s3:::sticker-buyer/*

  CloudFrontDistribution:
      Type: 'AWS::CloudFront::Distribution'
      Properties:
        DistributionConfig:
          Origins:
            - DomainName: !GetAtt [StickerBuyer, DomainName]
              Id: S3Origin
              S3OriginConfig:
                OriginAccessIdentity: ""
          Enabled: true
          DefaultRootObject: 'index.html'
          DefaultCacheBehavior:
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: 'redirect-to-https'
            AllowedMethods:
              - 'GET'
              - 'HEAD'
            CachedMethods:
              - 'GET'
              - 'HEAD'
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: 'none'
          PriceClass: 'PriceClass_100'
          ViewerCertificate:
            CloudFrontDefaultCertificate: true